# Exemple d'utilisation du template pour un PV pour WordPress
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  # Ajoute d'autres paramètres du PV ici, comme le chemin d'accès sur l'hôte, les options de montages, etc.

